#!/usr/bin/env python3
"""
Knowledge Graph Extraction – DeepSeek
Merged working extraction pipeline + updated 8-criterion confidence framework.

Pipeline:
1. Check previous confidence evaluation.
2. If needed, run the updated 8-criterion confidence framework.
3. Extract PDF text.
4. Chunk by page (2500 chars / 400 char overlap).
5. Extract KG triples with DeepSeek/Ollama.
6. Parse sentence references and confidence scores.
7. Deduplicate, keeping highest-confidence triples.
8. Save CSV and JSON.

Confidence scoreboard:
1. Structural Completeness                 /20 HARD FAIL
2. Peer Review Signals                     /20
3. Authorship & Community Alignment (IKAT) /25 HARD FAIL
4. Ethical Source Handling & Consent       /15 HARD FAIL
5. Metadata Completeness                   /10
6. Red Flag Absence                        /5  HARD FAIL
7. Experience Report Identification        /5
8. Domain Relevance                        /0  LOGGED ONLY

Hard-fail criteria override the numeric score.
"""

import sys
import json
import csv
import re
import time
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional
from datetime import datetime
from dataclasses import dataclass, field
from enum import Enum

import requests
import pdfplumber


# ============================================================
# Configuration
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "deepseek-r1:7b"

REJECT_THRESHOLD = 60
REVIEW_THRESHOLD = 75

LOG_DIR = Path("confidence_logs")
APPROVED_DIR = LOG_DIR / "approved"
REJECTED_DIR = LOG_DIR / "rejected"
REVIEW_DIR = LOG_DIR / "review"
REVIEW_QUEUE_FILE = Path("review_queue.csv")

# Confidence model evaluation
CONFIDENCE_CHUNK_WORD_SIZE = 1500
CONFIDENCE_CHUNK_OVERLAP = 200

# KG extraction
KG_URL = "http://localhost:11434/api/generate"
KG_CHUNK_SIZE = 2500
KG_CHUNK_OVERLAP = 400


COMMUNITY_KEYWORDS = [
    "garo", "mandi", "a'chik", "achik", "indigenous",
    "indigenous knowledge", "indigenous community", "community knowledge",
]

RED_FLAG_PHRASES = [
    "blog post", "personal blog", "wordpress.com", "blogspot.com",
    "breaking news", "news article", "press release",
    "for immediate release", "sponsored content", "buy now",
    "special offer", "limited time offer", "contact us today",
    "as an ai language model", "generated by chatgpt",
    "generated by artificial intelligence",
]

DATA_DRIVEN_SIGNALS = [
    "methodology", "methods", "materials and methods", "research design",
    "study design", "data collection", "data analysis", "sampling",
    "sample size", "participants", "respondents", "procedure",
    "survey", "questionnaire", "focus group", "interview", "interviews",
    "semi-structured interview", "in-depth interview", "fieldwork",
    "field study", "ethnographic", "case study", "qualitative",
    "quantitative", "statistical analysis", "thematic analysis",
    "regression", "coding scheme", "inter-rater reliability",
    "purposive sampling", "random sampling", "data were collected",
    "we interviewed", "we surveyed", "sample of",
]

EXPERIENCE_REPORT_SIGNALS = [
    "experience report", "in my experience", "in our experience",
    "personal reflection", "personal account", "anecdotal evidence",
    "i believe", "we believe", "in my opinion", "in our opinion",
    "this essay argues", "commentary", "op-ed", "viewpoint",
    "perspective piece", "reflective essay", "reflective account",
    "reflective practice", "as a practitioner", "drawing on my own",
    "narrative account", "memoir", "field experience",
    "no formal methodology", "without a research design",
]

NEGATION_CUES = [
    "no ", "not ", "without ", "lack of ",
    "lacking ", "absence of ", "none of ",
]


# ============================================================
# Confidence framework data classes
# ============================================================

class EvaluationOutcome(str, Enum):
    APPROVED = "APPROVED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    REJECTED = "REJECTED"


@dataclass
class CriterionResult:
    name: str
    score: int
    max_score: int
    passed: bool
    justification: str
    evaluated_by: str
    flags: List[str] = field(default_factory=list)
    hard_fail: bool = False
    hard_fail_triggered: bool = False


@dataclass
class EvaluationResult:
    paper_path: str
    paper_name: str
    timestamp: str
    total_score: int
    max_possible: int
    outcome: EvaluationOutcome
    criteria: List[CriterionResult] = field(default_factory=list)
    rejection_reason: Optional[str] = None
    review_reason: Optional[str] = None
    log_path: Optional[str] = None
    review_queue_path: Optional[str] = None
    model_used: str = OLLAMA_MODEL

    @property
    def score_pct(self) -> float:
        return round(self.total_score / self.max_possible * 100, 1) if self.max_possible else 0.0

    @property
    def accumulated_score(self) -> int:
        return self.total_score

    @property
    def hard_fail_criteria(self) -> List[CriterionResult]:
        return [c for c in self.criteria if c.hard_fail and c.hard_fail_triggered]


# ============================================================
# 1. Text extraction
# ============================================================

def extract_text_from_pdf(pdf_path: str) -> str:
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            page_text = page.extract_text()
            if page_text:
                text += f"\n===== Page {page_num} =====\n"
                text += page_text + "\n"
    return text


def normalise_text(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower()).strip()


# ============================================================
# 2. Updated confidence framework — model criteria 1–4
# ============================================================

def build_confidence_system_prompt() -> str:
    return """You are an expert academic paper evaluator for the P85 Mandi
Climate Knowledge Graph project.

Assess the paper against exactly four criteria below. Return ONLY valid JSON.
Do not include markdown or explanations outside JSON.

PROJECT CONTEXT
The project evaluates sources about the Mandi/Garo Indigenous community.
Evidence must be assessed carefully. Do not assume a criterion is satisfied
merely because a keyword appears. Use evidence from the paper.

CRITERION 1 — Structural Completeness (max 20, HARD FAIL)
Checks for:
- abstract
- introduction
- findings/results/discussion
- conclusion
- references
Allows genuine experience reports, but rejects clearly non-academic formats.
A hard fail should be true when the document is clearly non-academic or
structurally extremely incomplete and not a genuine experience report.

CRITERION 2 — Peer Review Signals (max 20, no hard fail)
Positive indicators only:
- DOI
- journal or conference name
- publisher information
- volume/issue/ISSN
- peer-review indicators
- formal academic formatting
Score based on the strength of the available evidence.

CRITERION 3 — Authorship & Community Alignment (IKAT) (max 25, HARD FAIL)
Check for:
- acknowledgement of the community
- respectful framing and correct terminology
- evidence of consultation or collaboration
- community participation or authorship
- non-extractive language and reciprocal framing
Hard fail if the paper uses clearly harmful/dehumanising language or has no
respectful community framing where the community is a substantive subject.

CRITERION 4 — Ethical Source Handling & Consent (max 15, HARD FAIL)
Check for:
- ethics approval or ethical process
- informed consent or equivalent permission
- cultural sensitivity/protocols
- avoidance of misrepresentation and harmful generalisations
Hard fail when harmful generalisation/misrepresentation is evident, or when a
paper collecting human/community knowledge has no ethical, consent, or cultural
handling evidence at all. Do not require a formal IRB phrase if contextual
ethical evidence exists.

IMPORTANT:
- Award points only when supported by the excerpt and metadata.
- Do not invent evidence.
- Return hard_fail_triggered true only for an actual hard-fail condition.
- flags should list specific concerns.

Required JSON:
{
  "criteria": [
    {
      "name": "Structural Completeness",
      "score": 0,
      "max_score": 20,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    },
    {
      "name": "Peer Review Signals",
      "score": 0,
      "max_score": 20,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    },
    {
      "name": "Authorship & Community Alignment (IKAT)",
      "score": 0,
      "max_score": 25,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    },
    {
      "name": "Ethical Source Handling & Consent",
      "score": 0,
      "max_score": 15,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    }
  ],
  "overall_recommendation": "..."
}"""


def chunk_paper_for_confidence(text: str) -> List[str]:
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + CONFIDENCE_CHUNK_WORD_SIZE, len(words))
        chunks.append(" ".join(words[start:end]))
        start += CONFIDENCE_CHUNK_WORD_SIZE - CONFIDENCE_CHUNK_OVERLAP
    return chunks


def build_confidence_user_prompt(
    chunk_text: str,
    metadata: Dict[str, Any],
    chunk_num: int,
    total_chunks: int,
) -> str:
    authors = metadata.get("authors", "")
    if isinstance(authors, list):
        authors = ", ".join(str(a) for a in authors)

    meta_str = "\n".join([
        f"Title: {metadata.get('title') or 'Unknown'}",
        f"Authors: {authors or 'Unknown'}",
        f"Year: {metadata.get('year') or 'Unknown'}",
        f"Journal: {metadata.get('journal') or 'Unknown'}",
        f"DOI: {metadata.get('doi') or 'Unknown'}",
    ])

    return f"""## Paper Metadata
{meta_str}

## Paper Excerpt (chunk {chunk_num} of {total_chunks})
{chunk_text}

Evaluate this excerpt against all four criteria and return only the required JSON."""


def extract_json_object(raw: str) -> Optional[Dict[str, Any]]:
    cleaned = re.sub(r"```json|```", "", raw).strip()
    cleaned = re.sub(r"<think>.*?</think>", "", cleaned,
                     flags=re.DOTALL | re.IGNORECASE).strip()
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group())
    except json.JSONDecodeError:
        return None


def call_confidence_ollama(
    system_prompt: str,
    user_prompt: str,
    model: str,
    retries: int = 2,
) -> Optional[str]:
    for attempt in range(retries):
        try:
            response = requests.post(
                OLLAMA_URL,
                json={
                    "model": model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    "stream": False,
                    "options": {
                        "temperature": 0.1,
                        "num_predict": 2048,
                    },
                },
                timeout=300,
            )

            if response.status_code == 200:
                return response.json().get("message", {}).get("content", "")

            print(
                f"   Ollama returned status {response.status_code} "
                f"(attempt {attempt + 1})"
            )

        except requests.exceptions.ConnectionError:
            print("   Cannot connect to Ollama. Is 'ollama serve' running?")
        except Exception as e:
            print(f"   Ollama error: {e}")

        time.sleep(2)

    return None


def fallback_confidence_criteria() -> List[CriterionResult]:
    specs = [
        ("Structural Completeness", 20, True),
        ("Peer Review Signals", 20, False),
        ("Authorship & Community Alignment (IKAT)", 25, True),
        ("Ethical Source Handling & Consent", 15, True),
    ]

    return [
        CriterionResult(
            name=name,
            score=0,
            max_score=max_score,
            passed=False,
            justification="Model evaluation failed — could not connect to Ollama or parse the response.",
            evaluated_by="fallback",
            flags=["Model unavailable"],
            hard_fail=hard_fail,
        )
        for name, max_score, hard_fail in specs
    ]


def evaluate_model_criteria(
    paper_text: str,
    metadata: Dict[str, Any],
    model: str,
) -> List[CriterionResult]:
    system_prompt = build_confidence_system_prompt()
    chunks = chunk_paper_for_confidence(paper_text)

    expected = [
        ("Structural Completeness", 20, True),
        ("Peer Review Signals", 20, False),
        ("Authorship & Community Alignment (IKAT)", 25, True),
        ("Ethical Source Handling & Consent", 15, True),
    ]

    if not chunks:
        return fallback_confidence_criteria()

    print(f"   Confidence evaluation: {len(chunks)} chunks.")

    accumulated = {
        name: {
            "scores": [],
            "justifications": [],
            "flags": [],
            "hard_fails": [],
        }
        for name, _, _ in expected
    }

    successful_chunks = 0

    for idx, chunk in enumerate(chunks, 1):
        print(f"   Confidence chunk {idx}/{len(chunks)}...", end=" ", flush=True)

        raw = call_confidence_ollama(
            system_prompt,
            build_confidence_user_prompt(chunk, metadata, idx, len(chunks)),
            model,
        )

        if not raw:
            print("failed")
            continue

        data = extract_json_object(raw)
        if not data or not isinstance(data.get("criteria"), list):
            print("parse error")
            continue

        successful_chunks += 1
        print("OK")

        items_by_name = {
            item.get("name", ""): item
            for item in data["criteria"]
            if isinstance(item, dict)
        }

        for name, max_score, _ in expected:
            item = items_by_name.get(name)
            if not item:
                continue

            try:
                score = int(item.get("score", 0))
            except (TypeError, ValueError):
                score = 0

            score = max(0, min(score, max_score))
            accumulated[name]["scores"].append(score)
            accumulated[name]["justifications"].append(
                str(item.get("justification", ""))
            )

            flags = item.get("flags", [])
            if isinstance(flags, list):
                accumulated[name]["flags"].extend(str(x) for x in flags)

            if item.get("hard_fail_triggered", False):
                accumulated[name]["hard_fails"].append(True)

        time.sleep(0.5)

    if successful_chunks == 0:
        return fallback_confidence_criteria()

    results = []

    for name, max_score, hard_fail in expected:
        acc = accumulated[name]
        scores = acc["scores"]
        score = max(scores) if scores else 0

        if scores:
            best_idx = scores.index(score)
            justification = acc["justifications"][best_idx]
        else:
            justification = "No usable model result was returned for this criterion."

        results.append(
            CriterionResult(
                name=name,
                score=score,
                max_score=max_score,
                passed=score > 0,
                justification=justification,
                evaluated_by="model",
                flags=list(dict.fromkeys(acc["flags"])),
                hard_fail=hard_fail,
                hard_fail_triggered=any(acc["hard_fails"]),
            )
        )

    return results


# ============================================================
# 3. Updated confidence framework — code criteria 5–8
# ============================================================

def check_metadata_completeness(metadata: Dict[str, Any]) -> CriterionResult:
    fields = {
        "title": 2,
        "authors": 2,
        "year": 2,
        "journal": 2,
        "doi": 2,
    }

    found = [f for f in fields if metadata.get(f)]
    missing = [f for f in fields if not metadata.get(f)]
    score = sum(fields[f] for f in found)

    return CriterionResult(
        name="Metadata Completeness",
        score=score,
        max_score=10,
        passed=score >= 5,
        justification=f"Metadata present: {found}. Missing: {missing}.",
        evaluated_by="code",
        flags=[f"Missing: {f}" for f in missing],
    )


def check_red_flags(text_lower: str) -> CriterionResult:
    found = [p for p in RED_FLAG_PHRASES if p in text_lower]

    has_references = bool(
        re.search(r"\breferences\b|\bbibliography\b|\breference list\b", text_lower)
    )

    ai_only = (
        bool(found)
        and all(p in {
            "as an ai language model",
            "generated by chatgpt",
            "generated by artificial intelligence",
        } for p in found)
    )

    if not found:
        score, triggered = 5, False
        justification = "No red-flag phrases detected."
    elif ai_only and has_references:
        score, triggered = 3, False
        justification = (
            "AI-generation indicators were found, but references are also "
            "present. Flagged for caution rather than hard failure."
        )
    else:
        score, triggered = 0, True
        justification = "Non-academic or serious source red flags were detected."

    return CriterionResult(
        name="Red Flag Absence",
        score=score,
        max_score=5,
        passed=not triggered,
        justification=justification,
        evaluated_by="code",
        flags=[f"Red flag: '{p}'" for p in found],
        hard_fail=True,
        hard_fail_triggered=triggered,
    )


def _has_unnegated_match(text: str, phrase: str, window_chars: int = 40) -> bool:
    start = 0
    while True:
        idx = text.find(phrase, start)
        if idx == -1:
            return False

        preceding = text[max(0, idx - window_chars):idx]
        if not any(cue in preceding for cue in NEGATION_CUES):
            return True

        start = idx + len(phrase)


def _dedupe_substring_hits(hits: List[str]) -> List[str]:
    hits_sorted = sorted(set(hits), key=len, reverse=True)
    kept = []
    for hit in hits_sorted:
        if not any(hit != existing and hit in existing for existing in kept):
            kept.append(hit)
    return kept


def check_data_driven_evidence(text_lower: str) -> Dict[str, Any]:
    data_hits = _dedupe_substring_hits([
        s for s in DATA_DRIVEN_SIGNALS
        if _has_unnegated_match(text_lower, s)
    ])

    experience_hits = _dedupe_substring_hits([
        s for s in EXPERIENCE_REPORT_SIGNALS
        if s in text_lower
    ])

    if experience_hits and not data_hits:
        verdict = "experience_report"
    elif experience_hits and data_hits and len(experience_hits) > len(data_hits):
        verdict = "experience_leaning"
    elif data_hits:
        verdict = "data_driven"
    else:
        verdict = "undetermined"

    return {
        "verdict": verdict,
        "data_driven_signals_found": data_hits,
        "experience_signals_found": experience_hits,
    }


def check_experience_report_identification(text_lower: str) -> CriterionResult:
    scan = check_data_driven_evidence(text_lower)
    verdict = scan["verdict"]
    experience_hits = scan["experience_signals_found"]
    data_hits = scan["data_driven_signals_found"]

    if verdict == "experience_report":
        score = 5
        justification = (
            "Paper appears narrative/experiential with no clear "
            "data-collection or methodology evidence."
        )
    elif verdict == "experience_leaning":
        score = 3
        justification = (
            "Experiential or reflective language is stronger than the "
            "detected methodology/data-driven signals."
        )
    elif verdict == "data_driven":
        score = 0
        justification = (
            "Paper appears to be a conventional data-driven research "
            "paper rather than an experience report."
        )
    else:
        score = 0
        justification = (
            "No strong experience-report or data-driven signals were detected."
        )

    flags = []
    if experience_hits:
        flags.append(f"Experience signals: {experience_hits[:8]}")
    if data_hits:
        flags.append(f"Data-driven signals: {data_hits[:8]}")

    return CriterionResult(
        name="Experience Report Identification",
        score=score,
        max_score=5,
        passed=True,
        justification=justification,
        evaluated_by="code",
        flags=flags,
    )


def check_domain_relevance(text_lower: str) -> CriterionResult:
    found = [k for k in COMMUNITY_KEYWORDS if k.lower() in text_lower]

    return CriterionResult(
        name="Domain Relevance",
        score=0,
        max_score=0,
        passed=True,
        justification=(
            f"Community/domain-related keywords were detected: {found}."
            if found else
            "No configured community/domain keywords were detected. "
            "This criterion is logged only and does not affect scoring."
        ),
        evaluated_by="code",
        flags=[] if found else ["No configured domain keywords found"],
    )


# ============================================================
# 4. Confidence logs / status
# ============================================================

def get_paper_status(pdf_path: str) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """
    Reads the NEW confidence_logs layout:
      confidence_logs/approved/
      confidence_logs/rejected/
      confidence_logs/review/

    Also understands the old rejection_logs layout so existing papers
    are not silently re-evaluated.
    """
    paper_stem = Path(pdf_path).stem

    candidates = []

    for directory in (APPROVED_DIR, REJECTED_DIR, REVIEW_DIR):
        if directory.exists():
            candidates.extend(directory.glob(f"*_{paper_stem}.json"))

    # Backward compatibility with the original working script.
    old_dir = Path("rejection_logs")
    if old_dir.exists():
        candidates.extend(old_dir.glob(f"*_*_{paper_stem}.json"))

    if not candidates:
        return None, None, None

    candidates.sort(key=lambda f: f.stat().st_mtime, reverse=True)
    latest = candidates[0]

    try:
        data = json.loads(latest.read_text(encoding="utf-8"))
        outcome = data.get("outcome")
        timestamp = data.get("timestamp") or datetime.fromtimestamp(
            latest.stat().st_mtime
        ).strftime("%Y%m%d_%H%M%S")
        return outcome, timestamp, str(latest)
    except Exception:
        return None, None, None


def save_evaluation_log(result: EvaluationResult, log_type: str) -> Path:
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    subdir = {
        "approval": APPROVED_DIR,
        "rejection": REJECTED_DIR,
        "review": REVIEW_DIR,
    }.get(log_type, LOG_DIR)

    subdir.mkdir(parents=True, exist_ok=True)

    safe_name = re.sub(r"[^\w\-]", "_", Path(result.paper_path).stem)[:50]
    log_path = subdir / f"{result.timestamp}_{log_type}_{safe_name}.json"

    data = {
        "paper": result.paper_path,
        "paper_name": result.paper_name,
        "timestamp": result.timestamp,
        "model_used": result.model_used,
        "outcome": result.outcome.value,
        "accumulated_score": result.accumulated_score,
        "total_score": result.total_score,
        "max_possible": result.max_possible,
        "score_pct": result.score_pct,
        "hard_fail_count": len(result.hard_fail_criteria),
        "hard_fail_criteria": [c.name for c in result.hard_fail_criteria],
        "thresholds": {
            "reject_below": REJECT_THRESHOLD,
            "manual_review_band": f"{REJECT_THRESHOLD}-{REVIEW_THRESHOLD}",
            "auto_approve_above": REVIEW_THRESHOLD,
        },
        "rejection_reason": result.rejection_reason,
        "review_reason": result.review_reason,
        "criteria": [
            {
                "name": c.name,
                "score": c.score,
                "max_score": c.max_score,
                "passed": c.passed,
                "hard_fail": c.hard_fail,
                "hard_fail_triggered": c.hard_fail_triggered,
                "evaluated_by": c.evaluated_by,
                "justification": c.justification,
                "flags": c.flags,
            }
            for c in result.criteria
        ],
        "next_steps": (
            "REJECTED — paper skipped. Review the hard-fail criteria and "
            "criterion justifications before reconsidering this source."
            if log_type == "rejection"
            else
            "MANUAL REVIEW — extraction is held pending human review."
            if log_type == "review"
            else
            "APPROVED — paper passed the scoreboard and is ready for "
            "knowledge graph extraction."
        ),
    }

    log_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return log_path


def append_review_queue(result: EvaluationResult) -> Path:
    write_header = not REVIEW_QUEUE_FILE.exists()

    with open(REVIEW_QUEUE_FILE, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)

        if write_header:
            writer.writerow([
                "timestamp", "paper_name", "paper_path", "model_used",
                "accumulated_score", "max_possible", "score_pct",
                "hard_fail_criteria", "review_reason", "status",
                "override_by", "override_note",
            ])

        writer.writerow([
            result.timestamp,
            result.paper_name,
            result.paper_path,
            result.model_used,
            result.accumulated_score,
            result.max_possible,
            result.score_pct,
            "; ".join(c.name for c in result.hard_fail_criteria),
            result.review_reason,
            "PENDING",
            "",
            "",
        ])

    return REVIEW_QUEUE_FILE


def run_confidence_check(
    pdf_path: str,
    metadata: Dict[str, Any],
    model: str,
) -> EvaluationResult:
    paper_path = Path(pdf_path)
    paper_name = paper_path.stem
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    print(f"\n1. Confidence evaluation for {paper_name}...")

    try:
        full_text = extract_text_from_pdf(str(paper_path))
        text_lower = normalise_text(full_text)
        print(f"   Extracted {len(text_lower.split())} words.")
    except Exception as e:
        print(f"   Text extraction failed: {e}")
        full_text = ""
        text_lower = ""

    print("2. Model evaluation (Criteria 1–4)...")
    model_criteria = evaluate_model_criteria(full_text, metadata, model)

    print("3. Code evaluation (Criteria 5–8)...")
    code_criteria = [
        check_metadata_completeness(metadata),
        check_red_flags(text_lower),
        check_experience_report_identification(text_lower),
        check_domain_relevance(text_lower),
    ]

    for c in code_criteria:
        print(f"   {c.name}: {c.score}/{c.max_score}")

    all_criteria = model_criteria + code_criteria

    total_score = sum(c.score for c in all_criteria)
    max_possible = sum(c.max_score for c in all_criteria)

    hard_fails = [c for c in all_criteria if c.hard_fail and c.hard_fail_triggered]

    if hard_fails:
        outcome = EvaluationOutcome.REJECTED
        rejection_reason = (
            "Hard-fail criterion triggered: " +
            "; ".join(f"{c.name} — {c.justification}" for c in hard_fails)
        )
        review_reason = None

    elif total_score < REJECT_THRESHOLD:
        outcome = EvaluationOutcome.REJECTED
        rejection_reason = (
            f"Accumulated score {total_score}/{max_possible} "
            f"({round(total_score / max_possible * 100, 1)}%) "
            f"is below the reject threshold of {REJECT_THRESHOLD}."
        )
        review_reason = None

    elif total_score <= REVIEW_THRESHOLD:
        outcome = EvaluationOutcome.MANUAL_REVIEW
        rejection_reason = None
        review_reason = (
            f"Accumulated score {total_score}/{max_possible} "
            f"({round(total_score / max_possible * 100, 1)}%) "
            f"is in the manual review band "
            f"({REJECT_THRESHOLD}-{REVIEW_THRESHOLD})."
        )

    else:
        outcome = EvaluationOutcome.APPROVED
        rejection_reason = None
        review_reason = None

    result = EvaluationResult(
        paper_path=str(paper_path),
        paper_name=paper_name,
        timestamp=timestamp,
        total_score=total_score,
        max_possible=max_possible,
        outcome=outcome,
        criteria=all_criteria,
        rejection_reason=rejection_reason,
        review_reason=review_reason,
        model_used=model,
    )

    if outcome == EvaluationOutcome.REJECTED:
        result.log_path = str(save_evaluation_log(result, "rejection"))
        print(f"4. REJECTED — {rejection_reason}")
        print(f"   Log: {result.log_path}")

    elif outcome == EvaluationOutcome.MANUAL_REVIEW:
        result.log_path = str(save_evaluation_log(result, "review"))
        result.review_queue_path = str(append_review_queue(result))
        print(f"4. MANUAL REVIEW — {review_reason}")
        print(f"   Log: {result.log_path}")
        print(f"   Review queue: {result.review_queue_path}")

    else:
        result.log_path = str(save_evaluation_log(result, "approval"))
        print(
            f"4. APPROVED — accumulated score "
            f"{total_score}/{max_possible} ({result.score_pct}%)"
        )
        print(f"   Log: {result.log_path}")

    return result


# ============================================================
# 5. KG extraction
# ============================================================

def chunk_text(text: str) -> List[Tuple[str, int]]:
    page_pattern = r"(===== Page \d+ =====\n)"
    parts = re.split(page_pattern, text)

    pages = []
    for i in range(1, len(parts), 2):
        if i + 1 >= len(parts):
            continue

        header = parts[i]
        content = parts[i + 1]
        match = re.search(r"===== Page (\d+) =====", header)
        page_num = int(match.group(1)) if match else 0
        pages.append((page_num, content))

    chunks = []

    for page_num, page_content in pages:
        if not page_content.strip():
            continue

        start = 0
        length = len(page_content)

        while start < length:
            end = min(start + KG_CHUNK_SIZE, length)
            chunks.append((page_content[start:end].strip(), page_num))
            start += KG_CHUNK_SIZE - KG_CHUNK_OVERLAP

    return chunks


def strip_deepseek_reasoning(raw: str) -> str:
    """
    Preserve the original working parser behaviour while also removing
    <think> blocks when a newer DeepSeek response format is returned.
    """
    raw = re.sub(r"<think>.*?</think>", "", raw,
                 flags=re.DOTALL | re.IGNORECASE)

    # Original working behaviour: discard text before the first structured
    # triple delimiter.
    for marker in ["(", "[", "{"]:
        idx = raw.find(marker)
        if idx != -1:
            raw = raw[idx:]
            break

    raw = re.sub(r"^```(?:cypher|json)?\n?", "", raw)
    raw = re.sub(r"\n?```$", "", raw)
    return raw.strip()


def make_kg_prompt(chunk: str) -> str:
    return f"""Read the paper and extract knowledge graph triples in these steps:
1. Identify informative sentences
2. Identify the main subject of each sentence
3. Extract as Subject–Predicate–Object. They should have a format like:
   (GaroWomen)-[ARE_KNOWN_AS]->(SkilledBeauticians)
4. Each triple needs to be referenced to a sentence, so extract the location
   of the sentence alongside the triple
5. Estimate a confidence score between 0.0 and 1.0 indicating how explicitly
   the sentence supports the triple:
   - 1.0 = the sentence directly states the triple verbatim
   - 0.8-0.9 = clearly implies the triple with slight paraphrasing
   - 0.5-0.7 = indirectly supports the triple, some inference needed
   - 0.0-0.4 = weak or ambiguous support, high inference

Output each triple and its reference and confidence on one line in this exact format:
(Subject)-[PREDICATE]->(Object) | Location: "sentence text" (Page X) | confidence: 0.95

Rules:
- Predicates: UPPER_CASE_WITH_UNDERSCORES
- Only extract explicit facts. No inference.
- If no triples, output nothing.

Passage:
{chunk}
"""


def parse_triples_with_reference(
    output: str,
    page_num: int,
) -> List[Dict[str, Any]]:
    triples = []

    for line in output.split("\n"):
        line = line.strip()

        triple_match = re.search(
            r"\(([^)]+)\)\s*-\s*\[:?([^\]]+)\]\s*->\s*\(([^)]+)\)",
            line,
        )

        if not triple_match:
            continue

        subject = triple_match.group(1).strip()
        predicate = triple_match.group(2).strip().upper()
        obj = triple_match.group(3).strip()

        ref_match = re.search(
            r'\|\s*Location:\s*["]?(.*?)["]?(?:\s*\(Page\s*(\d+)\))?',
            line,
            re.IGNORECASE,
        )

        if ref_match:
            sentence_ref = ref_match.group(1).strip()
            ref_page = ref_match.group(2) or str(page_num)
        else:
            parts = line.split("|", 1)
            sentence_ref = parts[1].strip() if len(parts) > 1 else "NO_REFERENCE"
            ref_page = str(page_num)

        confidence_match = re.search(
            r"confidence:\s*([0-9]*\.?[0-9]+)",
            line,
            re.IGNORECASE,
        )

        if confidence_match:
            confidence = max(
                0.0,
                min(1.0, float(confidence_match.group(1))),
            )
        else:
            confidence = 0.5

        triples.append({
            "subject": subject,
            "predicate": predicate,
            "object": obj,
            "source_section": f"Page {ref_page}",
            "confidence": confidence,
            "passage": f"({subject})-[:{predicate}]->({obj})",
            "sentence_ref": sentence_ref,
        })

    return triples


def extract_kg_chunk(
    chunk: str,
    page_num: int,
    model: str,
    retries: int = 2,
) -> Tuple[List[Dict[str, Any]], float]:
    prompt = make_kg_prompt(chunk)
    start_time = time.time()

    for attempt in range(retries):
        try:
            response = requests.post(
                KG_URL,
                json={
                    "model": model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.0,
                        "num_predict": 2048,
                    },
                },
                timeout=150,
            )

            elapsed = time.time() - start_time

            if response.status_code != 200:
                print(
                    f"HTTP {response.status_code} "
                    f"(attempt {attempt + 1})"
                )
                continue

            raw = response.json().get("response", "")
            cleaned = strip_deepseek_reasoning(raw)
            triples = parse_triples_with_reference(cleaned, page_num)

            if triples:
                return triples, elapsed

        except requests.exceptions.ConnectionError:
            print("Cannot connect to Ollama. Is 'ollama serve' running?")
        except Exception as e:
            print(f"Attempt {attempt + 1} error: {e}")

        time.sleep(1)

    return [], time.time() - start_time


def deduplicate(triples: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = {}

    for triple in triples:
        key = (
            f"{triple['subject'].lower()}|"
            f"{triple['predicate']}|"
            f"{triple['object'].lower()}"
        )

        if key not in seen:
            seen[key] = triple
            continue

        current_conf = triple.get("confidence", 0)
        existing_conf = seen[key].get("confidence", 0)

        if current_conf > existing_conf:
            seen[key] = triple
        elif (
            current_conf == existing_conf
            and len(triple.get("sentence_ref", ""))
            > len(seen[key].get("sentence_ref", ""))
        ):
            seen[key] = triple

    return list(seen.values())


def save_csv(triples: List[Dict[str, Any]], path: str, paper: str) -> None:
    fields = [
        "extraction_number", "paper", "subject", "predicate", "object",
        "source_section", "confidence", "passage", "sentence_ref",
    ]

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()

        for idx, triple in enumerate(triples, 1):
            writer.writerow({
                "extraction_number": idx,
                "paper": paper,
                "subject": triple.get("subject", ""),
                "predicate": triple.get("predicate", ""),
                "object": triple.get("object", ""),
                "source_section": triple.get("source_section", "Unknown"),
                "confidence": triple.get("confidence", 0.5),
                "passage": triple.get("passage", ""),
                "sentence_ref": triple.get("sentence_ref", ""),
            })


def save_json(triples: List[Dict[str, Any]], path: str, paper: str) -> None:
    data = []

    for idx, triple in enumerate(triples, 1):
        data.append({
            "extraction_number": idx,
            "paper": paper,
            "subject": triple["subject"],
            "predicate": triple["predicate"],
            "object": triple["object"],
            "source_section": triple["source_section"],
            "confidence": triple.get("confidence", 0.5),
            "passage": triple["passage"],
            "sentence_ref": triple["sentence_ref"],
        })

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def format_time(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.2f} sec"
    return f"{int(seconds // 60)}m {seconds % 60:.2f}s"


# ============================================================
# 6. Extraction routine
# ============================================================

def run_extraction(pdf_path: str, model: str) -> None:
    total_start = time.time()

    print("=" * 70)
    print("Knowledge Graph Extraction – DeepSeek")
    print(f"PDF: {pdf_path}")
    print(f"Model: {model}")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)

    full_text = extract_text_from_pdf(pdf_path)

    if not full_text.strip():
        print("No text extracted.")
        return

    chunks = chunk_text(full_text)
    print(f"\nCreated {len(chunks)} chunks")

    all_triples = []

    for idx, (chunk, page) in enumerate(chunks, 1):
        print(
            f"Chunk {idx}/{len(chunks)} (page ~{page})...",
            end=" ",
            flush=True,
        )

        triples, _ = extract_kg_chunk(chunk, page, model)
        all_triples.extend(triples)
        print(f"got {len(triples)} triples")
        time.sleep(0.2)

    unique = deduplicate(all_triples)
    base_name = Path(pdf_path).stem

    save_csv(unique, f"{base_name}_kg.csv", base_name)
    save_json(unique, f"{base_name}_kg.json", base_name)

    total_time = time.time() - total_start

    print(
        f"\nCOMPLETED! {len(unique)} unique triples "
        f"in {format_time(total_time)}"
    )

    if unique:
        avg_conf = sum(
            t.get("confidence", 0) for t in unique
        ) / len(unique)
        print(f"Average confidence: {avg_conf:.2f}")


# ============================================================
# 7. CLI
# ============================================================

def get_arg(name: str, default: str = "") -> str:
    if name in sys.argv:
        idx = sys.argv.index(name)
        if idx + 1 < len(sys.argv):
            return sys.argv[idx + 1]
    return default


def print_confidence_result(result: EvaluationResult) -> None:
    print("\n" + "=" * 95)
    print(f"{result.outcome.value} — {result.paper_name}")
    print(f"Model: {result.model_used}")

    if result.total_score >= 0:
        print(
            f"ACCUMULATED SCORE: {result.accumulated_score}/"
            f"{result.max_possible} ({result.score_pct}%)"
        )
        print(
            f"Bands: REJECTED < {REJECT_THRESHOLD} | "
            f"MANUAL REVIEW {REJECT_THRESHOLD}-{REVIEW_THRESHOLD} | "
            f"APPROVED > {REVIEW_THRESHOLD}"
        )

    print("-" * 95)

    print(
        f"{'#':<4}{'Criterion':<45}{'Score':<10}"
        f"{'Hard Fail?':<14}{'Status':<10}"
    )
    print("-" * 95)

    for idx, criterion in enumerate(result.criteria, 1):
        if not criterion.hard_fail:
            hard_status = "NO"
        elif criterion.hard_fail_triggered:
            hard_status = "TRIGGERED"
        else:
            hard_status = "YES"

        status = (
            "FAIL" if criterion.hard_fail_triggered
            else "OK" if criterion.passed
            else "LOW"
        )

        print(
            f"{idx:<4}{criterion.name:<45}"
            f"{criterion.score}/{criterion.max_score:<7}"
            f"{hard_status:<14}{status:<10}"
        )

    print("-" * 95)

    if result.hard_fail_criteria:
        print(
            "HARD FAILS TRIGGERED: " +
            ", ".join(c.name for c in result.hard_fail_criteria)
        )
    else:
        print("HARD FAILS TRIGGERED: None")

    if result.rejection_reason:
        print(f"Reason: {result.rejection_reason}")
    if result.review_reason:
        print(f"Reason: {result.review_reason}")

    print("=" * 95)


def main() -> None:
    if len(sys.argv) < 2:
        print(
            "Usage: python script_updated.py <pdf_path> "
            "[model_name] [--title ...] [--authors ...] "
            "[--year ...] [--journal ...] [--doi ...]"
        )
        sys.exit(1)

    pdf_path = sys.argv[1]

    model = "deepseek-r1:7b"
    if len(sys.argv) > 2 and not sys.argv[2].startswith("--"):
        model = sys.argv[2]

    metadata = {
        "title": get_arg("--title"),
        "authors": get_arg("--authors"),
        "year": get_arg("--year"),
        "journal": get_arg("--journal"),
        "doi": get_arg("--doi"),
    }

    # --------------------------------------------------------
    # Check previous confidence status.
    # --------------------------------------------------------

    outcome, timestamp, log_path = get_paper_status(pdf_path)

    if outcome == EvaluationOutcome.APPROVED.value:
        print(f"\nPaper previously APPROVED (log: {log_path})")
        print("Running extraction automatically...")
        run_extraction(pdf_path, model)
        return

    if outcome == EvaluationOutcome.REJECTED.value:
        print(f"\nPaper previously REJECTED (log: {log_path})")
        answer = input("Override and extract anyway? (y/N): ").strip().lower()

        if answer == "y":
            run_extraction(pdf_path, model)
        else:
            print("Extraction skipped.")
        return

    if outcome == EvaluationOutcome.MANUAL_REVIEW.value:
        print(f"\nPaper previously marked MANUAL REVIEW (log: {log_path})")
        answer = input("Override and extract anyway? (y/N): ").strip().lower()

        if answer == "y":
            run_extraction(pdf_path, model)
        else:
            print("Extraction skipped.")
        return

    # --------------------------------------------------------
    # No previous evaluation.
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("No previous confidence evaluation found for this paper.")
    print("Options:")
    print("  1) Run updated 8-criterion confidence check")
    print("  2) Extract anyway (bypass confidence)")
    print("  3) Exit")

    choice = input("Enter choice (1/2/3): ").strip()

    if choice == "1":
        result = run_confidence_check(
            pdf_path,
            metadata=metadata,
            model=model,
        )
        print_confidence_result(result)

        if result.outcome == EvaluationOutcome.REJECTED:
            print("\nExtraction skipped.")
            sys.exit(1)

        if result.outcome == EvaluationOutcome.MANUAL_REVIEW:
            answer = input(
                "\nOverride manual review and extract anyway? (y/N): "
            ).strip().lower()

            if answer != "y":
                print("Extraction skipped.")
                sys.exit(2)

            print("Manual override accepted — proceeding with extraction.")

        run_extraction(pdf_path, model)

    elif choice == "2":
        print(
            "\nWARNING: Bypassing confidence check — "
            "extraction may produce low-quality results."
        )
        run_extraction(pdf_path, model)

    else:
        print("Exiting.")
        sys.exit(0)


if __name__ == "__main__":
    main()