#!/usr/bin/env python3
"""
confidence_framework.py — Updated 8-Criterion Scoreboard

Keeps the original confidence-framework pipeline and function sequence:
1. Extract PDF text
2. Model evaluation
3. Code-based evaluation
4. Accumulate scores
5. Apply hard-fail rules
6. Determine outcome
7. Save logs/review queue
8. CLI output

Scoreboard:
1. Structural Completeness                 /20  HARD FAIL
2. Peer Review Signals                     /20
3. Authorship & Community Alignment (IKAT) /25  HARD FAIL
4. Ethical Source Handling & Consent       /15  HARD FAIL
5. Metadata Completeness                   /10
6. Red Flag Absence                        /5   HARD FAIL
7. Experience Report Identification        /5
8. Domain Relevance                        /0   LOGGED ONLY

Accumulated score: 100 points maximum.
Hard-fail criteria override the numeric score.
"""

import sys
import csv
import json
import re
import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import List, Dict, Any, Optional

import requests
import pdfplumber


# ============================================================
# Configuration
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "deepseek-r1:7b"

REJECT_THRESHOLD = 60
REVIEW_THRESHOLD = 75

LOG_DIR = Path("confidence_logs")
APPROVED_DIR = LOG_DIR / "approved"
REJECTED_DIR = LOG_DIR / "rejected"
REVIEW_DIR = LOG_DIR / "review"

REVIEW_QUEUE_FILE = Path("review_queue.csv")

COMMUNITY_KEYWORDS: List[str] = [
    "garo",
    "mandi",
    "a'chik",
    "achik",
    "indigenous",
    "indigenous knowledge",
    "indigenous community",
    "community knowledge",
]

RED_FLAG_PHRASES: List[str] = [
    "blog post",
    "personal blog",
    "wordpress.com",
    "blogspot.com",
    "breaking news",
    "news article",
    "press release",
    "for immediate release",
    "sponsored content",
    "buy now",
    "special offer",
    "limited time offer",
    "contact us today",
    "as an ai language model",
    "generated by chatgpt",
    "generated by artificial intelligence",
]

DATA_DRIVEN_SIGNALS: List[str] = [
    "methodology", "methods", "materials and methods", "research design",
    "study design", "data collection", "data analysis", "sampling",
    "sample size", "participants", "respondents", "procedure",
    "survey", "questionnaire", "focus group", "interview", "interviews",
    "semi-structured interview", "in-depth interview", "fieldwork",
    "field study", "ethnographic", "case study", "qualitative",
    "quantitative", "statistical analysis", "thematic analysis",
    "regression", "coding scheme", "inter-rater reliability",
    "purposive sampling", "random sampling", "data were collected",
    "we interviewed", "we surveyed", "sample of",
]

EXPERIENCE_REPORT_SIGNALS: List[str] = [
    "experience report", "in my experience", "in our experience",
    "personal reflection", "personal account", "anecdotal evidence",
    "i believe", "we believe", "in my opinion", "in our opinion",
    "this essay argues", "commentary", "op-ed", "viewpoint",
    "perspective piece", "reflective essay", "reflective account",
    "reflective practice", "as a practitioner", "drawing on my own",
    "narrative account", "memoir", "field experience",
    "no formal methodology", "without a research design",
]


# ============================================================
# Outcome enum
# ============================================================

class EvaluationOutcome(str, Enum):
    APPROVED = "APPROVED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    REJECTED = "REJECTED"


# ============================================================
# Data classes
# ============================================================

@dataclass
class CriterionResult:
    name: str
    score: int
    max_score: int
    passed: bool
    justification: str
    evaluated_by: str
    flags: List[str] = field(default_factory=list)
    hard_fail: bool = False
    hard_fail_triggered: bool = False


@dataclass
class EvaluationResult:
    paper_path: str
    paper_name: str
    timestamp: str
    total_score: int
    max_possible: int
    outcome: EvaluationOutcome
    criteria: List[CriterionResult] = field(default_factory=list)
    rejection_reason: Optional[str] = None
    review_reason: Optional[str] = None
    log_path: Optional[str] = None
    review_queue_path: Optional[str] = None
    model_used: str = OLLAMA_MODEL

    @property
    def score_pct(self) -> float:
        return round(
            self.total_score / self.max_possible * 100, 1
        ) if self.max_possible else 0.0

    @property
    def passed(self) -> bool:
        return self.outcome == EvaluationOutcome.APPROVED

    @property
    def accumulated_score(self) -> int:
        return self.total_score

    @property
    def hard_fail_criteria(self) -> List[CriterionResult]:
        return [
            c for c in self.criteria
            if c.hard_fail and c.hard_fail_triggered
        ]


# ============================================================
# 1. Text Extraction from PDF
# ============================================================

def extract_text_from_pdf(pdf_path: str) -> str:
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            page_text = page.extract_text()
            if page_text:
                text += f"\n===== Page {page_num} =====\n"
                text += page_text + "\n"
    return text


# ============================================================
# Helpers
# ============================================================

def normalise_text(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower()).strip()


def contains_any(text: str, phrases: List[str]) -> bool:
    return any(phrase.lower() in text for phrase in phrases)


def count_matches(text: str, phrases: List[str]) -> int:
    return sum(1 for phrase in phrases if phrase.lower() in text)


def extract_json_object(raw: str) -> Optional[Dict[str, Any]]:
    cleaned = re.sub(r"```json|```", "", raw).strip()

    # Remove common DeepSeek-style reasoning tags if present.
    cleaned = re.sub(
        r"<think>.*?</think>",
        "",
        cleaned,
        flags=re.DOTALL | re.IGNORECASE,
    ).strip()

    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if not match:
        return None

    try:
        return json.loads(match.group())
    except json.JSONDecodeError:
        return None


# ============================================================
# 2. System prompt — model criteria 1–4
# ============================================================

def build_system_prompt() -> str:
    return """You are an expert academic paper evaluator for the P85 Mandi
Climate Knowledge Graph project.

Assess the paper against exactly four criteria below. Return ONLY valid JSON.
Do not include markdown or explanations outside JSON.

PROJECT CONTEXT
The project evaluates sources about the Mandi/Garo Indigenous community.
Evidence must be assessed carefully. Do not assume a criterion is satisfied
merely because a keyword appears. Use evidence from the paper.

CRITERION 1 — Structural Completeness (max 20, HARD FAIL)
Checks for basic academic structure:
- abstract
- introduction
- findings/results/discussion
- conclusion
- references
Allows genuine experience reports, but rejects clearly non-academic formats.
A hard fail should be true when the document is clearly non-academic or
structurally extremely incomplete and not a genuine experience report.

CRITERION 2 — Peer Review Signals (max 20, no hard fail)
Positive indicators only:
- DOI
- journal or conference name
- publisher information
- volume/issue/ISSN
- peer-review indicators
- formal academic formatting
Score based on the strength of the available evidence.

CRITERION 3 — Authorship & Community Alignment (IKAT) (max 25, HARD FAIL)
Check for:
- acknowledgement of the community
- respectful framing and correct terminology
- evidence of consultation or collaboration
- community participation or authorship
- non-extractive language and reciprocal framing
Hard fail if the paper uses clearly harmful/dehumanising language or has no
respectful community framing where the community is a substantive subject.

CRITERION 4 — Ethical Source Handling & Consent (max 15, HARD FAIL)
Check for:
- ethics approval or ethical process
- informed consent or equivalent permission
- cultural sensitivity/protocols
- avoidance of misrepresentation and harmful generalisations
Hard fail when harmful generalisation/misrepresentation is evident, or when a
paper collecting human/community knowledge has no ethical, consent, or cultural
handling evidence at all. Do not require a formal IRB phrase if contextual
ethical evidence exists.

IMPORTANT:
- Award points only when supported by the excerpt and metadata.
- Do not invent evidence.
- Return hard_fail_triggered true only for an actual hard-fail condition.
- flags should list specific concerns.

Required JSON format:

{
  "criteria": [
    {
      "name": "Structural Completeness",
      "score": 0,
      "max_score": 20,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    },
    {
      "name": "Peer Review Signals",
      "score": 0,
      "max_score": 20,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    },
    {
      "name": "Authorship & Community Alignment (IKAT)",
      "score": 0,
      "max_score": 25,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    },
    {
      "name": "Ethical Source Handling & Consent",
      "score": 0,
      "max_score": 15,
      "justification": "...",
      "flags": [],
      "hard_fail_triggered": false
    }
  ],
  "overall_recommendation": "..."
}"""


CHUNK_WORD_SIZE = 1500
CHUNK_OVERLAP = 200


def chunk_paper(paper_text: str) -> List[str]:
    words = paper_text.split()
    chunks = []
    start = 0

    while start < len(words):
        end = min(start + CHUNK_WORD_SIZE, len(words))
        chunks.append(" ".join(words[start:end]))
        start += CHUNK_WORD_SIZE - CHUNK_OVERLAP

    return chunks


def build_user_prompt(
    chunk_text: str,
    metadata: Dict[str, Any],
    chunk_num: int,
    total_chunks: int
) -> str:
    meta_str = "\n".join([
        f"Title: {metadata.get('title', 'Unknown')}",
        f"Authors: {metadata.get('authors', 'Unknown')}",
        f"Year: {metadata.get('year', 'Unknown')}",
        f"Journal: {metadata.get('journal', 'Unknown')}",
        f"DOI: {metadata.get('doi', 'Unknown')}",
    ])

    return f"""## Paper Metadata
{meta_str}

## Paper Excerpt (chunk {chunk_num} of {total_chunks})
{chunk_text}

Evaluate this excerpt against all four criteria and return only the required JSON."""


# ============================================================
# 3. Ollama API call
# ============================================================

def call_ollama(
    system_prompt: str,
    user_prompt: str,
    retries: int = 2
) -> Optional[str]:
    for attempt in range(retries):
        try:
            response = requests.post(
                OLLAMA_URL,
                json={
                    "model": OLLAMA_MODEL,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    "stream": False,
                    "format": {
                        "type": "object",
                        "properties": {
                            "criteria": {
                                "type": "array",
                                "minItems": 4,
                                "maxItems": 4,
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "enum": [
                                                "Structural Completeness",
                                                "Peer Review Signals",
                                                "Authorship & Community Alignment (IKAT)",
                                                "Ethical Source Handling & Consent"
                                            ]
                                        },
                                        "score": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 25
                                        },
                                        "max_score": {
                                            "type": "integer"
                                        },
                                        "justification": {
                                            "type": "string"
                                        },
                                        "flags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "hard_fail_triggered": {
                                            "type": "boolean"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "score",
                                        "max_score",
                                        "justification",
                                        "flags",
                                        "hard_fail_triggered"
                                    ]
                                }
                            },
                            "overall_recommendation": {
                                "type": "string"
                            }
                        },
                        "required": ["criteria"]
                    },
                    "options": {
                        "temperature": 0.1,
                        "num_predict": 2048,
                    }
                },
                timeout=300
            )

            if response.status_code == 200:
                return response.json().get(
                    "message", {}
                ).get("content", "")

            print(
                f"   Ollama returned status {response.status_code} "
                f"(attempt {attempt + 1})"
            )
            print(f"   Response: {response.text[:200]}")

        except requests.exceptions.ConnectionError:
            print(
                "   Cannot connect to Ollama. "
                "Is 'ollama serve' running?"
            )
            if attempt == retries - 1:
                return None

        except Exception as e:
            print(f"   Ollama error: {e}")

        time.sleep(2)

    return None


def parse_model_response(raw: str) -> Optional[List[Dict[str, Any]]]:
    data = extract_json_object(raw)
    if not data:
        return None
    return data.get("criteria", [])


# ============================================================
# 4. Model-based criteria evaluation (Criteria 1–4)
# ============================================================

def evaluate_with_model(
    paper_text: str,
    metadata: Dict[str, Any]
) -> List[CriterionResult]:
    system_prompt = build_system_prompt()
    chunks = chunk_paper(paper_text)
    total_chunks = len(chunks)

    if not chunks:
        return _fallback_criteria()

    print(
        f"   Split into {total_chunks} chunks of "
        f"~{CHUNK_WORD_SIZE} words each."
    )

    expected = [
        ("Structural Completeness", 20, True),
        ("Peer Review Signals", 20, False),
        ("Authorship & Community Alignment (IKAT)", 25, True),
        ("Ethical Source Handling & Consent", 15, True),
    ]

    accumulated: Dict[str, Dict[str, Any]] = {
        name: {
            "scores": [],
            "justifications": [],
            "flags": [],
            "hard_fails": [],
            "max_score": max_score,
            "hard_fail": hard_fail,
        }
        for name, max_score, hard_fail in expected
    }

    successful_chunks = 0

    for idx, chunk in enumerate(chunks, start=1):
        print(
            f"   Chunk {idx}/{total_chunks}...",
            end=" ",
            flush=True
        )

        user_prompt = build_user_prompt(
            chunk,
            metadata,
            idx,
            total_chunks
        )

        raw = call_ollama(system_prompt, user_prompt)

        print("\n--- RAW MODEL RESPONSE ---")
        print(raw)
        print("--- END RAW MODEL RESPONSE ---\n")

        if not raw:
            print("failed (skipped)")
            continue

        criteria_data = parse_model_response(raw)

        if not criteria_data:
            print("parse error (skipped)")
            print("\n--- RAW MODEL RESPONSE ---")
            print(raw)
            print("--- END RAW MODEL RESPONSE ---\n")
            continue

        successful_chunks += 1
        print("OK")

        items_by_name = {
            item.get("name", ""): item
            for item in criteria_data
            if isinstance(item, dict)
        }

        for name, max_score, _ in expected:
            item = items_by_name.get(name)

            if item is None:
                continue

            try:
                raw_score = int(item.get("score", 0))
                returned_max = int(item.get("max_score", max_score))

                # Some local models return a 0-5 rating even though the
                # framework criterion is worth 15, 20 or 25 points.
                # Convert that rating proportionally to the criterion scale.
                if returned_max > 0 and returned_max != max_score:
                    score = round((raw_score / returned_max) * max_score)
                else:
                    score = raw_score

                score = max(0, min(score, max_score))

            except (TypeError, ValueError, ZeroDivisionError):
                score = 0

            score = max(0, min(score, max_score))

            accumulated[name]["scores"].append(score)
            accumulated[name]["justifications"].append(
                item.get("justification", "")
            )

            flags = item.get("flags", [])
            if isinstance(flags, list):
                accumulated[name]["flags"].extend(
                    str(flag) for flag in flags
                )

            if item.get("hard_fail_triggered", False):
                accumulated[name]["hard_fails"].append(True)

        time.sleep(0.5)

    if successful_chunks == 0:
        print(
            "   All chunks failed — falling back to zero scores."
        )
        return _fallback_criteria()

    print(
        f"   {successful_chunks}/{total_chunks} chunks "
        f"evaluated successfully."
    )

    results = []

    for name, max_score, hard_fail in expected:
        acc = accumulated[name]
        scores = acc["scores"]

        # Same accumulation style as the original framework:
        # keep the strongest evidence found across successful chunks.
        score = max(scores) if scores else 0

        if scores:
            best_idx = scores.index(max(scores))
            justification = (
                acc["justifications"][best_idx]
                if best_idx < len(acc["justifications"])
                else "No justification."
            )
        else:
            justification = (
                "No usable model result was returned for this criterion."
            )

        unique_flags = list(
            dict.fromkeys(acc["flags"])
        )

        results.append(
            CriterionResult(
                name=name,
                score=score,
                max_score=max_score,
                passed=score > 0,
                justification=justification,
                evaluated_by="model",
                flags=unique_flags,
                hard_fail=hard_fail,
                hard_fail_triggered=any(
                    acc["hard_fails"]
                ),
            )
        )

    return results


def _fallback_criteria() -> List[CriterionResult]:
    specs = [
        ("Structural Completeness", 20, True),
        ("Peer Review Signals", 20, False),
        ("Authorship & Community Alignment (IKAT)", 25, True),
        ("Ethical Source Handling & Consent", 15, True),
    ]

    return [
        CriterionResult(
            name=name,
            score=0,
            max_score=max_score,
            passed=False,
            justification=(
                "Model evaluation failed — could not connect to Ollama "
                "or parse the response."
            ),
            evaluated_by="fallback",
            flags=["Model unavailable"],
            hard_fail=hard_fail,
            hard_fail_triggered=False,
        )
        for name, max_score, hard_fail in specs
    ]


# ============================================================
# 5. Code-based criteria (Criteria 5–8)
# ============================================================

def check_metadata_completeness(
    metadata: Dict[str, Any]
) -> CriterionResult:
    field_scores = {
        "title": 2,
        "authors": 2,
        "year": 2,
        "journal": 2,
        "doi": 2,
    }

    score = sum(
        points
        for field_name, points in field_scores.items()
        if metadata.get(field_name)
    )

    found = [
        field_name
        for field_name in field_scores
        if metadata.get(field_name)
    ]

    missing = [
        field_name
        for field_name in field_scores
        if not metadata.get(field_name)
    ]

    return CriterionResult(
        name="Metadata Completeness",
        score=score,
        max_score=10,
        passed=score >= 5,
        justification=(
            f"Metadata present: {found}. "
            f"Missing: {missing}."
        ),
        evaluated_by="code",
        flags=[
            f"Missing: {field_name}"
            for field_name in missing
        ] if missing else [],
        hard_fail=False,
        hard_fail_triggered=False,
    )


def check_red_flags(text_lower: str) -> CriterionResult:
    found = [
        phrase
        for phrase in RED_FLAG_PHRASES
        if phrase in text_lower
    ]

    has_references = bool(
        re.search(
            r"\breferences\b|\bbibliography\b|\breference list\b",
            text_lower
        )
    )

    ai_only = (
        len(found) > 0
        and all(
            phrase in {
                "as an ai language model",
                "generated by chatgpt",
                "generated by artificial intelligence",
            }
            for phrase in found
        )
    )

    if not found:
        score = 5
        triggered = False
        justification = "No red-flag phrases detected."

    elif ai_only and has_references:
        score = 3
        triggered = False
        justification = (
            "AI-generation indicators were found, but references are also "
            "present. Flagged for caution rather than hard failure."
        )

    else:
        score = 0
        triggered = True
        justification = (
            "Non-academic or serious source red flags were detected."
        )

    return CriterionResult(
        name="Red Flag Absence",
        score=score,
        max_score=5,
        passed=not triggered,
        justification=justification,
        evaluated_by="code",
        flags=[
            f"Red flag: '{phrase}'"
            for phrase in found
        ],
        hard_fail=True,
        hard_fail_triggered=triggered,
    )


# ============================================================
# 5b. Experience Report Identification
# ============================================================

NEGATION_CUES = [
    "no ",
    "not ",
    "without ",
    "lack of ",
    "lacking ",
    "absence of ",
    "none of ",
]


def _has_unnegated_match(
    text_lower: str,
    phrase: str,
    window_chars: int = 40
) -> bool:
    start = 0

    while True:
        idx = text_lower.find(phrase, start)

        if idx == -1:
            return False

        preceding = text_lower[
            max(0, idx - window_chars):idx
        ]

        if not any(
            cue in preceding
            for cue in NEGATION_CUES
        ):
            return True

        start = idx + len(phrase)


def _dedupe_substring_hits(
    hits: List[str]
) -> List[str]:
    hits_sorted = sorted(
        set(hits),
        key=len,
        reverse=True
    )

    kept: List[str] = []

    for hit in hits_sorted:
        if not any(
            hit != kept_hit and hit in kept_hit
            for kept_hit in kept
        ):
            kept.append(hit)

    return kept


def check_data_driven_evidence(
    text_lower: str
) -> Dict[str, Any]:
    raw_data_hits = [
        signal
        for signal in DATA_DRIVEN_SIGNALS
        if _has_unnegated_match(
            text_lower,
            signal
        )
    ]

    raw_experience_hits = [
        signal
        for signal in EXPERIENCE_REPORT_SIGNALS
        if signal in text_lower
    ]

    data_hits = _dedupe_substring_hits(
        raw_data_hits
    )

    experience_hits = _dedupe_substring_hits(
        raw_experience_hits
    )

    if experience_hits and not data_hits:
        verdict = "experience_report"

    elif (
        experience_hits
        and data_hits
        and len(experience_hits) > len(data_hits)
    ):
        verdict = "experience_leaning"

    elif data_hits:
        verdict = "data_driven"

    else:
        verdict = "undetermined"

    return {
        "verdict": verdict,
        "data_driven_signals_found": data_hits,
        "experience_signals_found": experience_hits,
    }


def check_experience_report_identification(
    text_lower: str
) -> CriterionResult:
    """
    Criterion 7 — maximum 5, no hard fail.

    This keeps the existing data-driven vs experience-report signal
    detection, but exposes it as its own criterion because the new
    framework explicitly requires Experience Report Identification.
    """

    scan = check_data_driven_evidence(text_lower)

    verdict = scan["verdict"]
    experience_hits = scan[
        "experience_signals_found"
    ]
    data_hits = scan[
        "data_driven_signals_found"
    ]

    if verdict == "experience_report":
        score = 5
        justification = (
            "Paper appears narrative/experiential with no clear "
            "data-collection or methodology evidence."
        )

    elif verdict == "experience_leaning":
        score = 3
        justification = (
            "Experiential or reflective language is stronger than the "
            "detected methodology/data-driven signals."
        )

    elif verdict == "data_driven":
        score = 0
        justification = (
            "Paper appears to be a conventional data-driven research "
            "paper rather than an experience report."
        )

    else:
        score = 0
        justification = (
            "No strong experience-report or data-driven signals were "
            "detected."
        )

    flags = []

    if experience_hits:
        flags.append(
            f"Experience signals: {experience_hits[:8]}"
        )

    if data_hits:
        flags.append(
            f"Data-driven signals: {data_hits[:8]}"
        )

    return CriterionResult(
        name="Experience Report Identification",
        score=score,
        max_score=5,
        passed=True,
        justification=justification,
        evaluated_by="code",
        flags=flags,
        hard_fail=False,
        hard_fail_triggered=False,
    )


def check_domain_relevance(
    text_lower: str
) -> CriterionResult:
    found_keywords = [
        keyword
        for keyword in COMMUNITY_KEYWORDS
        if keyword.lower() in text_lower
    ]

    relevant = len(found_keywords) > 0

    if relevant:
        justification = (
            "Community/domain-related keywords were detected: "
            f"{found_keywords}."
        )
    else:
        justification = (
            "No configured community/domain keywords were detected. "
            "This criterion is logged only and does not affect scoring."
        )

    return CriterionResult(
        name="Domain Relevance",
        score=0,
        max_score=0,
        passed=True,
        justification=justification,
        evaluated_by="code",
        flags=[] if relevant else [
            "No configured domain keywords found"
        ],
        hard_fail=False,
        hard_fail_triggered=False,
    )


# ============================================================
# 6. Output writers
# ============================================================

def save_evaluation_log(
    result: EvaluationResult,
    log_type: str
) -> Path:
    LOG_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    if log_type == "approval":
        subdir = APPROVED_DIR
    elif log_type == "rejection":
        subdir = REJECTED_DIR
    elif log_type == "review":
        subdir = REVIEW_DIR
    else:
        subdir = LOG_DIR

    subdir.mkdir(
        parents=True,
        exist_ok=True
    )

    safe_name = re.sub(
        r"[^\w\-]",
        "_",
        Path(result.paper_path).stem
    )[:50]

    log_path = subdir / (
        f"{result.timestamp}_{log_type}_{safe_name}.json"
    )

    hard_fail_names = [
        criterion.name
        for criterion in result.hard_fail_criteria
    ]

    data = {
        "paper": result.paper_path,
        "paper_name": result.paper_name,
        "timestamp": result.timestamp,
        "model_used": result.model_used,
        "outcome": result.outcome.value,
        "accumulated_score": result.accumulated_score,
        "total_score": result.total_score,
        "max_possible": result.max_possible,
        "score_pct": result.score_pct,
        "hard_fail_count": len(
            result.hard_fail_criteria
        ),
        "hard_fail_criteria": hard_fail_names,
        "thresholds": {
            "reject_below": REJECT_THRESHOLD,
            "manual_review_band": (
                f"{REJECT_THRESHOLD}-{REVIEW_THRESHOLD}"
            ),
            "auto_approve_above": REVIEW_THRESHOLD,
        },
        "rejection_reason": result.rejection_reason,
        "review_reason": result.review_reason,
        "criteria": [
            {
                "name": criterion.name,
                "score": criterion.score,
                "max_score": criterion.max_score,
                "passed": criterion.passed,
                "hard_fail": criterion.hard_fail,
                "hard_fail_triggered": (
                    criterion.hard_fail_triggered
                ),
                "evaluated_by": criterion.evaluated_by,
                "justification": criterion.justification,
                "flags": criterion.flags,
            }
            for criterion in result.criteria
        ],
        "next_steps": (
            "REJECTED — paper skipped. Review the hard-fail criteria and "
            "criterion justifications before reconsidering this source."
            if log_type == "rejection"
            else
            "MANUAL REVIEW — extraction is held pending human review."
            if log_type == "review"
            else
            "APPROVED — paper passed the scoreboard and is ready for "
            "knowledge graph extraction."
        ),
    }

    log_path.write_text(
        json.dumps(
            data,
            indent=2,
            ensure_ascii=False
        ),
        encoding="utf-8"
    )

    return log_path


def append_review_queue(
    result: EvaluationResult
) -> Path:
    write_header = not REVIEW_QUEUE_FILE.exists()

    with open(
        REVIEW_QUEUE_FILE,
        "a",
        newline="",
        encoding="utf-8"
    ) as file:
        writer = csv.writer(file)

        if write_header:
            writer.writerow([
                "timestamp",
                "paper_name",
                "paper_path",
                "model_used",
                "accumulated_score",
                "max_possible",
                "score_pct",
                "hard_fail_criteria",
                "review_reason",
                "status",
                "override_by",
                "override_note",
            ])

        writer.writerow([
            result.timestamp,
            result.paper_name,
            result.paper_path,
            result.model_used,
            result.accumulated_score,
            result.max_possible,
            result.score_pct,
            "; ".join(
                criterion.name
                for criterion in result.hard_fail_criteria
            ),
            result.review_reason,
            "PENDING",
            "",
            "",
        ])

    return REVIEW_QUEUE_FILE


# ============================================================
# 7. Main pipeline function
# ============================================================

def run_confidence_check(
    pdf_path: str,
    metadata: Optional[Dict[str, Any]] = None,
    override_approve: Optional[str] = None,
) -> EvaluationResult:
    paper_path = Path(pdf_path)
    paper_name = paper_path.stem
    metadata = metadata or {}
    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    if override_approve:
        print(
            f"[OVERRIDE] {paper_name} manually approved: "
            f"{override_approve}"
        )

        return EvaluationResult(
            paper_path=str(paper_path),
            paper_name=paper_name,
            timestamp=timestamp,
            total_score=-1,
            max_possible=100,
            outcome=EvaluationOutcome.APPROVED,
            review_reason=(
                f"Manual override: {override_approve}"
            ),
            model_used=OLLAMA_MODEL,
        )

    print(
        f"1. Extracting text from {paper_name}..."
    )

    try:
        full_text = extract_text_from_pdf(
            str(paper_path)
        )
        text_lower = normalise_text(full_text)

        print(
            f"   Extracted "
            f"{len(text_lower.split())} words."
        )

    except Exception as e:
        print(
            f"   Text extraction failed: {e}"
        )
        full_text = ""
        text_lower = ""

    print(
        "2. Running model evaluation "
        "(Criteria 1–4)..."
    )

    model_criteria = evaluate_with_model(
        full_text,
        metadata
    )

    print(
        "3. Running code evaluation "
        "(Criteria 5–8)..."
    )

    code_criteria = [
        check_metadata_completeness(metadata),
        check_red_flags(text_lower),
        check_experience_report_identification(
            text_lower
        ),
        check_domain_relevance(text_lower),
    ]

    for criterion in code_criteria:
        print(
            f"   {criterion.name}: "
            f"{criterion.score}/"
            f"{criterion.max_score}"
        )

    all_criteria = (
        model_criteria + code_criteria
    )

    # Criterion 8 has max_score=0 and score=0, so the accumulated
    # score remains out of 100.
    total_score = sum(
        criterion.score
        for criterion in all_criteria
    )

    max_possible = sum(
        criterion.max_score
        for criterion in all_criteria
    )

    triggered_hard_fails = [
        criterion
        for criterion in all_criteria
        if (
            criterion.hard_fail
            and criterion.hard_fail_triggered
        )
    ]

    # ========================================================
    # Determine outcome
    # ========================================================

    if triggered_hard_fails:
        outcome = EvaluationOutcome.REJECTED

        rejection_reason = (
            "Hard-fail criterion triggered: "
            + "; ".join(
                f"{criterion.name} — "
                f"{criterion.justification}"
                for criterion in triggered_hard_fails
            )
        )

        review_reason = None

    elif total_score < REJECT_THRESHOLD:
        outcome = EvaluationOutcome.REJECTED

        rejection_reason = (
            f"Accumulated score "
            f"{total_score}/{max_possible} "
            f"({round(total_score / max_possible * 100, 1)}%) "
            f"is below the reject threshold of "
            f"{REJECT_THRESHOLD}."
        )

        review_reason = None

    elif total_score <= REVIEW_THRESHOLD:
        outcome = EvaluationOutcome.MANUAL_REVIEW

        rejection_reason = None

        review_reason = (
            f"Accumulated score "
            f"{total_score}/{max_possible} "
            f"({round(total_score / max_possible * 100, 1)}%) "
            f"is in the manual review band "
            f"({REJECT_THRESHOLD}-{REVIEW_THRESHOLD})."
        )

    else:
        outcome = EvaluationOutcome.APPROVED
        rejection_reason = None
        review_reason = None

    result = EvaluationResult(
        paper_path=str(paper_path),
        paper_name=paper_name,
        timestamp=timestamp,
        total_score=total_score,
        max_possible=max_possible,
        outcome=outcome,
        criteria=all_criteria,
        rejection_reason=rejection_reason,
        review_reason=review_reason,
        model_used=OLLAMA_MODEL,
    )

    # ========================================================
    # Write outputs
    # ========================================================

    if outcome == EvaluationOutcome.REJECTED:
        log_path = save_evaluation_log(
            result,
            "rejection"
        )

        result.log_path = str(log_path)

        print(
            f"4. REJECTED — {rejection_reason}"
        )

        print(f"   Log: {log_path}")

    elif outcome == EvaluationOutcome.MANUAL_REVIEW:
        log_path = save_evaluation_log(
            result,
            "review"
        )

        result.log_path = str(log_path)

        review_queue_path = append_review_queue(
            result
        )

        result.review_queue_path = str(
            review_queue_path
        )

        print(
            f"4. MANUAL REVIEW — {review_reason}"
        )

        print(f"   Log: {log_path}")

        print(
            f"   Review queue: "
            f"{review_queue_path}"
        )

    else:
        log_path = save_evaluation_log(
            result,
            "approval"
        )

        result.log_path = str(log_path)

        print(
            f"4. APPROVED — accumulated score "
            f"{total_score}/{max_possible} "
            f"({result.score_pct}%)"
        )

        print(f"   Log: {log_path}")

    print("Done!")

    return result


# ============================================================
# 8. CLI
# ============================================================

def _print_result(
    result: EvaluationResult
) -> None:
    labels = {
        EvaluationOutcome.APPROVED: "APPROVED",
        EvaluationOutcome.MANUAL_REVIEW: "MANUAL REVIEW",
        EvaluationOutcome.REJECTED: "REJECTED",
    }

    print(
        f"\n{'=' * 95}"
    )

    print(
        f"{labels[result.outcome]} — "
        f"{result.paper_name}"
    )

    print(
        f"Model: {result.model_used}"
    )

    if result.total_score >= 0:
        print(
            f"ACCUMULATED SCORE: "
            f"{result.accumulated_score}/"
            f"{result.max_possible} "
            f"({result.score_pct}%)"
        )

        print(
            "Bands: "
            f"REJECTED < {REJECT_THRESHOLD} | "
            f"MANUAL REVIEW "
            f"{REJECT_THRESHOLD}-{REVIEW_THRESHOLD} | "
            f"APPROVED > {REVIEW_THRESHOLD}"
        )

    print("-" * 95)

    print(
        f"{'#':<4}"
        f"{'Criterion':<45}"
        f"{'Score':<10}"
        f"{'Hard Fail?':<14}"
        f"{'Status':<10}"
    )

    print("-" * 95)

    for index, criterion in enumerate(
        result.criteria,
        start=1
    ):
        if not criterion.hard_fail:
            hard_fail_status = "NO"

        elif criterion.hard_fail_triggered:
            hard_fail_status = "TRIGGERED"

        else:
            hard_fail_status = "YES"

        status = (
            "FAIL"
            if criterion.hard_fail_triggered
            else
            "OK"
            if criterion.passed
            else
            "LOW"
        )

        print(
            f"{index:<4}"
            f"{criterion.name:<45}"
            f"{criterion.score}/"
            f"{criterion.max_score:<7}"
            f"{hard_fail_status:<14}"
            f"{status:<10}"
        )

    print("-" * 95)

    if result.hard_fail_criteria:
        print(
            "HARD FAILS TRIGGERED: "
            + ", ".join(
                criterion.name
                for criterion in result.hard_fail_criteria
            )
        )
    else:
        print(
            "HARD FAILS TRIGGERED: None"
        )

    print(
        f"FINAL OUTCOME: "
        f"{result.outcome.value}"
    )

    print("=" * 95)

    print(
        "\nDETAILED SCOREBOARD:"
    )

    for index, criterion in enumerate(
        result.criteria,
        start=1
    ):
        print(
            f"\n{index}. {criterion.name}"
        )

        print(
            f"   Score: "
            f"{criterion.score}/"
            f"{criterion.max_score}"
        )

        print(
            f"   Evaluated by: "
            f"{criterion.evaluated_by}"
        )

        print(
            f"   Hard fail criterion: "
            f"{criterion.hard_fail}"
        )

        print(
            f"   Hard fail triggered: "
            f"{criterion.hard_fail_triggered}"
        )

        print(
            f"   Justification: "
            f"{criterion.justification}"
        )

        for flag in criterion.flags:
            print(
                f"   FLAG: {flag}"
            )

    if result.rejection_reason:
        print(
            f"\nReason: "
            f"{result.rejection_reason}"
        )

    if result.review_reason:
        print(
            f"\nReason: "
            f"{result.review_reason}"
        )

    if result.review_queue_path:
        print(
            f"Review queue: "
            f"{result.review_queue_path}"
        )

    if result.log_path:
        print(
            f"Log: "
            f"{result.log_path}"
        )

    print("=" * 95)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "P85 Confidence Framework — "
            "8-Criterion Academic Source Scoreboard"
        )
    )

    parser.add_argument(
        "pdf_path",
        help="Path to the PDF file"
    )

    parser.add_argument(
        "--title",
        default=""
    )

    parser.add_argument(
        "--authors",
        default=""
    )

    parser.add_argument(
        "--year",
        default=""
    )

    parser.add_argument(
        "--journal",
        default=""
    )

    parser.add_argument(
        "--doi",
        default=""
    )

    parser.add_argument(
        "--model",
        default=OLLAMA_MODEL,
        help=(
            f"Ollama model to use "
            f"(default: {OLLAMA_MODEL})"
        )
    )

    parser.add_argument(
        "--override-approve",
        default=None,
        help=(
            "Manually approve a MANUAL_REVIEW paper "
            "with a justification string"
        )
    )

    args = parser.parse_args()

    meta = {
        "title": args.title,
        "authors": [
            author.strip()
            for author in args.authors.split(",")
            if author.strip()
        ],
        "year": args.year,
        "journal": args.journal,
        "doi": args.doi,
    }

    OLLAMA_MODEL = args.model

    result = run_confidence_check(
        args.pdf_path,
        metadata=meta,
        override_approve=args.override_approve,
    )

    _print_result(result)

    sys.exit(
        0
        if result.outcome == EvaluationOutcome.APPROVED
        else
        2
        if result.outcome == EvaluationOutcome.MANUAL_REVIEW
        else
        1
    )
