#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "EAT-40005 demo hosting (zero-budget, no paid compute)"

# ── Stage 1: Tailscale Funnel exposes local Ollama publicly ───────────────
stage "Tailscale: expose Ollama via Funnel"
say "The hosted API will call back to THIS machine's Ollama over a public"
say "HTTPS hostname, never a third-party model provider. That hostname comes"
say "from Tailscale Funnel."
say ""
if command -v tailscale >/dev/null 2>&1; then
  note "Tailscale CLI found."
else
  warn "Tailscale CLI not found on PATH."
  open_url "https://tailscale.com/download/windows"
  step "Download and install Tailscale for Windows, then sign in (any"
  step "provider -- Google/Microsoft/GitHub -- is fine for a personal tailnet)."
  pause "Press Enter once Tailscale is installed and you're signed in"
fi
say ""
say "Funnel has to be turned on for your tailnet the first time. Exact CLI"
say "flags change between Tailscale versions, so follow their own current"
say "docs rather than a flag this wizard might get wrong:"
open_url "https://tailscale.com/kb/1223/funnel"
step "Enable Funnel for your tailnet if prompted (one-time, in the admin console)."
step "Run this in a terminal to expose Ollama's port (11434) publicly:"
note "    tailscale funnel 11434"
step "Leave that command running (or use its background/bg mode per the docs"
step "above) -- the public hostname disappears if it's stopped."
step "In another terminal, run: tailscale funnel status"
step "Copy the https://<something>.ts.net hostname it reports (host only,"
step "no scheme, no trailing slash, no path)."
ask TAILSCALE_FUNNEL_HOST "Paste the Tailscale Funnel hostname:"
write_env TRUSTED_LLM_HOST "$TAILSCALE_FUNNEL_HOST"
note "This exact hostname also goes into llm_endpoint.py's TRUSTED_LLM_HOST"
note "check on the hosted side -- Stage 3 below sets it there too."

# ── Stage 2: Render account + connect repo + Dockerfile.serve ─────────────
stage "Render.com: create the web service"
say "Free tier, automatic HTTPS, builds straight from a Dockerfile in the repo."
open_url "https://dashboard.render.com/register"
step "Sign up (GitHub sign-in is simplest -- it also connects your repos)."
step "New + → Web Service → connect the EAT-40005-Extraction GitHub repo."
step "Environment: Docker. Dockerfile Path: Dockerfile.serve (not the default"
step "Dockerfile -- that one is the team's interactive dev container)."
step "Instance Type: Free."
step "Do NOT click Create yet -- the next stage sets required env vars first,"
step "and Render will prompt for them during the same setup flow."
confirm "Reached the \"Environment Variables\" section of the new-service form?"

# ── Stage 3: environment variables ─────────────────────────────────────────
stage "Render: environment variables"
say "Add each of these as an environment variable in that same Render form."
say "For the three NEO4J_* values, open your LOCAL .env file yourself and"
say "copy them across -- this wizard deliberately does not print secrets"
say "from it to this terminal."
note "    (Windows)  notepad .env"
pause "Press Enter once you have .env open to copy from"
say ""
say "Set these on Render (key = value):"
step "NEO4J_URI       = (from your .env)"
step "NEO4J_USERNAME  = (from your .env)"
step "NEO4J_PASSWORD  = (from your .env)"
step "OLLAMA_MODEL         = mistral:7b"
step "OLLAMA_URL           = https://${TAILSCALE_FUNNEL_HOST}/api/generate"
step "CONFIDENCE_OLLAMA_URL= https://${TAILSCALE_FUNNEL_HOST}/api/chat"
step "TRUSTED_LLM_HOST     = ${TAILSCALE_FUNNEL_HOST}"
note "Narrower than ALLOW_EXTERNAL_LLM=1: this pins exactly this one hostname"
note "as trusted, so the guard still refuses every other external host."
say ""
say "Now a fresh admin secret -- Render needs it as an env var, and you'll"
say "type the SAME value into the admin UI's secret prompt when using it."
ADMIN_UPLOAD_SECRET=$(python -c "import secrets; print(secrets.token_urlsafe(32))")
printf '  %sgenerated:%s %s\n' "$GREEN" "$RESET" "$ADMIN_UPLOAD_SECRET"
warn "Save that value now (password manager, sticky note) -- it will not be"
warn "shown again by this wizard, and it is never committed to the repo."
step "ADMIN_UPLOAD_SECRET  = ${ADMIN_UPLOAD_SECRET}"
write_env ADMIN_UPLOAD_SECRET "$ADMIN_UPLOAD_SECRET"
note "Also saved to your local .env, so a local --neo4j --serve run can use"
note "the same admin secret if you want to test the admin screen locally."
pause "Press Enter once every variable above is entered in Render, then click Create Web Service"

# ── Stage 4: confirm the deploy is live ────────────────────────────────────
stage "Confirm the API is live"
say "Render will build Dockerfile.serve and deploy. First build is typically"
say "a few minutes -- watch the Logs tab for \"RAG API listening on\"."
pause "Press Enter once the Render dashboard shows the service as Live"
step "Copy the public URL Render shows at the top of the service page"
step "(https://<something>.onrender.com)."
ask RENDER_API_URL "Paste the Render service URL (no trailing slash):"
write_env HOSTED_API_URL "$RENDER_API_URL"
say "Checking ${RENDER_API_URL}/health ..."
if curl -fsS -m 15 "${RENDER_API_URL}/health" 2>/dev/null | grep -q '"status"'; then
  printf '  %s✓ healthy%s\n' "$GREEN" "$RESET"
else
  warn "couldn't confirm /health -- check Render's Logs tab for errors"
  warn "(a free instance that was asleep can take ~30s to wake; try again)"
fi

# ── Stage 5: build and deploy the static web app ───────────────────────────
stage "Build and deploy the Flutter web app"
say "Builds the web app pointed at the hosted API, then publishes it to"
say "GitHub Pages via an orphan gh-pages branch (free, same repo)."
step "Building..."
( cd flutter_application && flutter build web --dart-define="API_BASE_URL=${RENDER_API_URL}" )
say ""
say "Now publish flutter_application/build/web to the gh-pages branch:"
note "    cd flutter_application/build/web"
note "    git init -q"
note "    git add -A"
note "    git commit -q -m \"Deploy demo site\""
note "    git push -f <your-repo-ssh-or-https-url> HEAD:gh-pages"
note "    cd -"
step "Replace <your-repo-...-url> with this repo's own remote (check: git remote -v)."
pause "Press Enter once that push has completed"
open_url "https://github.com/Aryan3337/EAT-40005-Extraction/settings/pages"
step "Under Build and deployment → Source: Deploy from a branch."
step "Branch: gh-pages, folder: / (root). Save."
step "GitHub shows the published URL once it finishes (can take a minute)."
ask GHPAGES_URL "Paste the GitHub Pages URL once it's live:"
write_env HOSTED_WEB_URL "$GHPAGES_URL"

finish
say "Hosted API:   ${RENDER_API_URL}"
say "Hosted site:  ${GHPAGES_URL}"
warn "Remember: ADMIN_UPLOAD_SECRET must match between what you saved above"
warn "and what you type into the admin screen's secret prompt."
warn "Live LLM answers depend on this machine's Ollama + the Funnel staying"
warn "up; the three cached demo questions and all retrieval/citations work"
warn "even if this machine is off."
